### ISSUE TITLE
Request : Add LFS support

### ISSUE THREAD

**Issue by oraklesekt** [jusdepatate/info.sh#8]
Hello, can you add Linux From Scratch support please? I don't use it but it's racist if you don't add it

**Comment by bc1bb** [comment]
It doesn't have native curl so it will be hard,
Compilation takes a lot of time and I don't have enough time.

**Comment by bc1bb** [comment]
I also can't detect them, i need to do support for all of them like [I've done for NuTyX](
https://github.com/jusdepatate/info.sh/commit/80f7bd038d311d97dbc4ef325366b3a087f383b6), it'll be hard :/

**Comment by bc1bb** [comment]
Rewrite will have a better OS detection so all LFS will be compatible
