### ISSUE TITLE
Ajout d'informations supplémentaires

### ISSUE THREAD

**Issue by Leeo97one** [jusdepatate/info.sh#9]
Quelques idées en vrac, j'en ajouterai d'autres au fur et à mesure.

PCI et modules :
```
lspci -k
```
OpenGL :
```
glxinfo -B
```
Logs/Journaux du démarrage actuel :
```
journalctl -b
```
Entrées UEFI :
```
efibootmgr -v
```
Disques et partitions :
```
parted -l
```

**Comment by bc1bb** [comment]
> lspci -k

Ni Termux, ni WSL me donnent de résultat sur celui la ahah

> glxinfo -B

Pas built-in Ubuntu WSL

> journalctl -b

```
No journal files were found.
-- No entries --
```

> efibootmgr -v

Pas built-in Ubuntu WSL

> parted -l

```
Kernel not configured for semaphores (System V IPC). Not using udev synchronisation code.
```


Bon... je vais me faire une vm et bosser sur ca un de ces quatres :D

**Comment by bc1bb** [comment]
Apres avoir réfléchit, si aucune de ses commandes ne sont fournit avec les environnement que j'ai ca ne ferai que ajouter des dependaces donc, au final je pense pas le faire
